//! Numerical parity tests: cross-validate Peregrine against PyTorch reference data.
//!
//! Reference data is generated by `tests/generate_reference.py`.
//! Run: cargo test --test pytorch_parity

use peregrine::nn;
use peregrine::optim::Adam;
use peregrine::tensor::Tensor;
use std::fs::File;
use std::io::Read;

const FIXTURES: &str = "tests/fixtures";

// --- Binary format helpers ---

fn load_tensor(path: &str) -> (Vec<usize>, Vec<f32>) {
    let mut file = File::open(path).unwrap_or_else(|_| {
        panic!(
            "Missing fixture: {}. Run: .venv/bin/python tests/generate_reference.py",
            path
        );
    });
    let mut buf = Vec::new();
    file.read_to_end(&mut buf).unwrap();

    let ndim = u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]) as usize;
    let mut shape = Vec::with_capacity(ndim);
    for i in 0..ndim {
        let off = 4 + i * 4;
        shape.push(u32::from_le_bytes([buf[off], buf[off + 1], buf[off + 2], buf[off + 3]]) as usize);
    }
    let data_offset = 4 + ndim * 4;
    let num_floats = shape.iter().product::<usize>();
    let mut data = Vec::with_capacity(num_floats);
    for i in 0..num_floats {
        let off = data_offset + i * 4;
        data.push(f32::from_le_bytes([buf[off], buf[off + 1], buf[off + 2], buf[off + 3]]));
    }
    (shape, data)
}

fn load_vec_u32(path: &str) -> Vec<usize> {
    let mut file = File::open(path).unwrap();
    let mut buf = Vec::new();
    file.read_to_end(&mut buf).unwrap();

    let len = u32::from_le_bytes([buf[0], buf[1], buf[2], buf[3]]) as usize;
    let mut v = Vec::with_capacity(len);
    for i in 0..len {
        let off = 4 + i * 4;
        v.push(u32::from_le_bytes([buf[off], buf[off + 1], buf[off + 2], buf[off + 3]]) as usize);
    }
    v
}

fn load_peregrine(path: &str) -> Tensor {
    let (shape, data) = load_tensor(path);
    Tensor::new(data, shape, false)
}

fn load_peregrine_param(path: &str) -> Tensor {
    let (shape, data) = load_tensor(path);
    Tensor::new(data, shape, true)
}

fn max_abs_error(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "length mismatch: {} vs {}", a.len(), b.len());
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| (x - y).abs())
        .fold(0.0f32, f32::max)
}

fn max_rel_error(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len());
    a.iter()
        .zip(b.iter())
        .map(|(x, y)| {
            let denom = x.abs().max(y.abs()).max(1e-8);
            (x - y).abs() / denom
        })
        .fold(0.0f32, f32::max)
}

// --- Tests ---

#[test]
fn parity_matmul() {
    let a = load_peregrine(&format!("{FIXTURES}/matmul_a.bin"));
    let b = load_peregrine(&format!("{FIXTURES}/matmul_b.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/matmul_c.bin"));

    let c = a.matmul(&b);
    let err = max_abs_error(&c.data(), &expected);
    assert!(err < 1e-4, "matmul max abs error: {err}");
}

#[test]
fn parity_matmul_rect() {
    let a = load_peregrine(&format!("{FIXTURES}/matmul_rect_a.bin"));
    let b = load_peregrine(&format!("{FIXTURES}/matmul_rect_b.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/matmul_rect_c.bin"));

    let c = a.matmul(&b);
    let err = max_abs_error(&c.data(), &expected);
    assert!(err < 1e-4, "matmul rect max abs error: {err}");
}

#[test]
fn parity_softmax() {
    let x = load_peregrine(&format!("{FIXTURES}/softmax_input.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/softmax_output.bin"));

    let y = x.softmax(-1);
    let err = max_abs_error(&y.data(), &expected);
    assert!(err < 1e-6, "softmax max abs error: {err}");
}

#[test]
fn parity_softmax_large_values() {
    let x = load_peregrine(&format!("{FIXTURES}/softmax_large_input.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/softmax_large_output.bin"));

    let y = x.softmax(-1);
    let err = max_abs_error(&y.data(), &expected);
    assert!(err < 1e-6, "softmax large values max abs error: {err}");
}

#[test]
fn parity_log_softmax() {
    let x = load_peregrine(&format!("{FIXTURES}/log_softmax_input.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/log_softmax_output.bin"));

    let y = x.log_softmax(-1);
    let err = max_abs_error(&y.data(), &expected);
    assert!(err < 1e-5, "log_softmax max abs error: {err}");
}

#[test]
fn parity_layernorm() {
    let x = load_peregrine(&format!("{FIXTURES}/layernorm_input.bin"));
    let gamma = load_peregrine_param(&format!("{FIXTURES}/layernorm_gamma.bin"));
    let beta = load_peregrine_param(&format!("{FIXTURES}/layernorm_beta.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/layernorm_output.bin"));

    let y = x.layer_norm(&gamma, &beta, 64);
    let err = max_abs_error(&y.data(), &expected);
    assert!(err < 1e-5, "layernorm max abs error: {err}");
}

#[test]
fn parity_cross_entropy() {
    let logits = load_peregrine(&format!("{FIXTURES}/ce_logits.bin"));
    let targets = load_vec_u32(&format!("{FIXTURES}/ce_targets.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ce_loss.bin"));

    let loss = nn::cross_entropy_loss(&logits, &targets);
    let err = (loss.data()[0] - expected[0]).abs();
    assert!(err < 1e-5, "cross_entropy max abs error: {err} (got {}, expected {})", loss.data()[0], expected[0]);
}

#[test]
fn parity_elementwise_add() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let y = load_peregrine(&format!("{FIXTURES}/ew_y.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_add.bin"));
    let err = max_abs_error(&x.add(&y).data(), &expected);
    assert!(err < 1e-6, "add max abs error: {err}");
}

#[test]
fn parity_elementwise_sub() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let y = load_peregrine(&format!("{FIXTURES}/ew_y.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_sub.bin"));
    let err = max_abs_error(&x.sub(&y).data(), &expected);
    assert!(err < 1e-6, "sub max abs error: {err}");
}

#[test]
fn parity_elementwise_mul() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let y = load_peregrine(&format!("{FIXTURES}/ew_y.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_mul.bin"));
    let err = max_abs_error(&x.mul(&y).data(), &expected);
    assert!(err < 1e-6, "mul max abs error: {err}");
}

#[test]
fn parity_elementwise_div() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let y = load_peregrine(&format!("{FIXTURES}/ew_y.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_div.bin"));
    let err = max_abs_error(&x.div(&y).data(), &expected);
    assert!(err < 1e-5, "div max abs error: {err}");
}

#[test]
fn parity_elementwise_neg() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_neg.bin"));
    let err = max_abs_error(&x.neg().data(), &expected);
    assert!(err < 1e-7, "neg max abs error: {err}");
}

#[test]
fn parity_elementwise_exp() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_exp.bin"));
    let err = max_abs_error(&x.exp().data(), &expected);
    assert!(err < 1e-5, "exp max abs error: {err}");
}

#[test]
fn parity_elementwise_log() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x_pos.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_log.bin"));
    let err = max_abs_error(&x.log().data(), &expected);
    assert!(err < 1e-6, "log max abs error: {err}");
}

#[test]
fn parity_elementwise_sqrt() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x_pos.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_sqrt.bin"));
    let err = max_abs_error(&x.sqrt().data(), &expected);
    assert!(err < 1e-6, "sqrt max abs error: {err}");
}

#[test]
fn parity_elementwise_abs() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_abs.bin"));
    let err = max_abs_error(&x.abs().data(), &expected);
    assert!(err < 1e-7, "abs max abs error: {err}");
}

#[test]
fn parity_elementwise_sin() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_sin.bin"));
    let err = max_abs_error(&x.sin().data(), &expected);
    assert!(err < 1e-6, "sin max abs error: {err}");
}

#[test]
fn parity_elementwise_cos() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_cos.bin"));
    let err = max_abs_error(&x.cos().data(), &expected);
    assert!(err < 1e-6, "cos max abs error: {err}");
}

#[test]
fn parity_elementwise_tanh() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_tanh.bin"));
    let err = max_abs_error(&x.tanh().data(), &expected);
    assert!(err < 1e-6, "tanh max abs error: {err}");
}

#[test]
fn parity_elementwise_relu() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_relu.bin"));
    let err = max_abs_error(&x.relu().data(), &expected);
    assert!(err < 1e-7, "relu max abs error: {err}");
}

#[test]
fn parity_elementwise_sigmoid() {
    let x = load_peregrine(&format!("{FIXTURES}/ew_x.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/ew_sigmoid.bin"));
    let err = max_abs_error(&x.sigmoid().data(), &expected);
    assert!(err < 1e-6, "sigmoid max abs error: {err}");
}

#[test]
fn parity_adam_step() {
    let (shape, w_data) = load_tensor(&format!("{FIXTURES}/adam_w_init.bin"));
    let (_, grad_data) = load_tensor(&format!("{FIXTURES}/adam_grad.bin"));
    let (_, expected) = load_tensor(&format!("{FIXTURES}/adam_w_after.bin"));

    // Create a parameter tensor with the initial weights
    let w = Tensor::new(w_data, shape, true);

    // Manually set the gradient to match PyTorch's gradient
    w.set_grad(grad_data);

    // Run one Adam step
    let mut opt = Adam::new(vec![w.clone()], 1e-3);
    opt.step();

    let err = max_abs_error(&w.data(), &expected);
    assert!(err < 1e-6, "adam step max abs error: {err}");
}

#[test]
fn parity_mlp_training() {
    // Load initial weights (same as PyTorch)
    let w1 = load_peregrine_param(&format!("{FIXTURES}/mlp_w1.bin"));
    let b1 = load_peregrine_param(&format!("{FIXTURES}/mlp_b1.bin"));
    let w2 = load_peregrine_param(&format!("{FIXTURES}/mlp_w2.bin"));
    let b2 = load_peregrine_param(&format!("{FIXTURES}/mlp_b2.bin"));
    let w3 = load_peregrine_param(&format!("{FIXTURES}/mlp_w3.bin"));
    let b3 = load_peregrine_param(&format!("{FIXTURES}/mlp_b3.bin"));

    let x_train = load_peregrine(&format!("{FIXTURES}/mlp_x_train.bin"));
    let targets = load_vec_u32(&format!("{FIXTURES}/mlp_targets_train.bin"));

    let (_, expected_losses) = load_tensor(&format!("{FIXTURES}/mlp_losses.bin"));
    let (_, expected_w1) = load_tensor(&format!("{FIXTURES}/mlp_w1_final.bin"));
    let (_, expected_w2) = load_tensor(&format!("{FIXTURES}/mlp_w2_final.bin"));
    let (_, expected_w3) = load_tensor(&format!("{FIXTURES}/mlp_w3_final.bin"));

    let params = vec![
        w1.clone(), b1.clone(), w2.clone(), b2.clone(), w3.clone(), b3.clone(),
    ];
    let mut opt = Adam::new(params, 1e-3);

    let mut losses = Vec::new();
    for step in 0..10 {
        // Forward: h1 = relu(x @ w1 + b1)
        let h1 = x_train.matmul(&w1).add_bias(&b1).relu();
        // h2 = relu(h1 @ w2 + b2)
        let h2 = h1.matmul(&w2).add_bias(&b2).relu();
        // logits = h2 @ w3 + b3
        let logits = h2.matmul(&w3).add_bias(&b3);

        let loss = nn::cross_entropy_loss(&logits, &targets);
        let loss_val = loss.data()[0];
        losses.push(loss_val);

        // Check loss matches PyTorch at each step
        let loss_err = (loss_val - expected_losses[step]).abs();
        let rel_err = loss_err / expected_losses[step].abs().max(1e-8);
        assert!(
            rel_err < 1e-4,
            "step {step}: loss relative error {rel_err} (peregrine={loss_val}, pytorch={})",
            expected_losses[step]
        );

        loss.backward();
        opt.step();
        opt.zero_grad();
    }

    // Check final weights
    let w1_err = max_rel_error(&w1.data(), &expected_w1);
    let w2_err = max_rel_error(&w2.data(), &expected_w2);
    let w3_err = max_rel_error(&w3.data(), &expected_w3);

    assert!(w1_err < 1e-3, "w1 final max rel error: {w1_err}");
    assert!(w2_err < 1e-3, "w2 final max rel error: {w2_err}");
    assert!(w3_err < 1e-3, "w3 final max rel error: {w3_err}");
}
