pub mod cpu_pool;
#[cfg(target_arch = "aarch64")]
pub mod simd_kernels;
pub mod tensor;
pub mod nn;
pub mod debug;
pub mod optim;
pub mod serial;
pub mod quant;
pub mod sparse;
pub mod huffman;
pub mod gguf;
pub mod safetensors;
pub mod hf_config;
#[cfg(feature = "hf")]
pub mod hf_hub;
pub mod random;
pub mod init;
pub mod fft;
pub mod linalg;
pub mod transforms;
pub mod rl;
pub mod rlm;
pub mod envs;
pub mod attention;
pub mod speculative;
pub mod thermal;
pub mod sched;
pub mod models;
#[cfg(target_arch = "aarch64")]
pub mod amx;

#[cfg(feature = "metal")]
pub mod metal;

#[cfg(feature = "comm")]
pub mod comm;
